### ISSUE TITLE
Unable to run hub detect on dotnet core app (Nuget) in debian linux environment 

### ISSUE THREAD

**Issue by AlexRamey** [blackducksoftware/hub-detect#351]
## Expected behavior
* Hub Detect works on a dotnet core app in a Debian Linux environment
## Actual behavior
* Error during BOM Tool "preparing for extraction" step: com.blackducksoftware.integration.hub.detect.exception.DetectUserFriendlyException: Unable to find a nuget executable even though nuget applied.
## Steps to Reproduce
* We're doing this within a docker container, so the environment is clean. Here's our Dockerfile: 

```docker
FROM microsoft/dotnet:2.1-sdk

RUN apt-get update && apt-get -y install default-jre

WORKDIR work

COPY . .

RUN dotnet build src/x.y.z/x.y.z.csproj
```
* From our project directory (where this Dockerfile is located) we build the image:
```bash
docker build -t local-dotnetcore:latest .
```

* Then to invoke hub-detect, we run the image as a container:
```bash
docker run -e BLACKDUCK_USERNAME -e BLACKDUCK_PASSWORD -e BLACKDUCK_URL local-dotnetcore:latest bash -c "./hubdetect.sh"
```

* Where hubdetect.sh contains:
```bash
#!/bin/bash

set -o errexit -o nounset -o xtrace -o pipefail

bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) \
    --blackduck.url=${BLACKDUCK_URL} \
    --blackduck.hub.username=${BLACKDUCK_USERNAME} \
    --blackduck.password=${BLACKDUCK_PASSWORD}
```
* And we get this issue when searching for BOM tools:
```bash
. . .
Preparation for extraction
. . . 
FAILED:NUGET - Solution - Exception occured: com.blackducksoftware.integration.hub.detect.exception.DetectUserFriendlyException: Unable to find a nuget executable even though nuget applied.
```

## Version
**Detect Version:** 4.4.1

**Language Version:** netcoreapp2.1

**Base Docker Image:** microsoft/dotnet:2.1-sdk

**OS:** From inside the container:
```bash
root@9fdb6bf00626:/work# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by taikuukaits** [comment]
We do not yet support dotnetcore for Nuget. We are adding support in 5.0.0 of detect.

**Comment by AlexRamey** [comment]
Thanks @taikuukaits .What is the 5.0.0 timeline looking like?

**Comment by imbeyondboredom** [comment]
@taikuukaits it looks like you all are making progress on this. Any possibility you can give a rough timeline? If this was going to take over month then I would spend time and patch it... if it's going to be in weeks then I'd likely just wait.

**Comment by taikuukaits** [comment]
Detect 5.0.0 is scheduled for QA next week. I do not know when it will be through QA.

You are welcome to try and patch it, the new inspector is located here:
https://github.com/blackducksoftware/blackduck-nuget-inspector

We have a branch for this work, but it is still likely to change dramatically as we are still in progress of moving the inspectors and going through 5.0.0 work at large. This branch was made from an earlier version of 4.

https://github.com/blackducksoftware/hub-detect/tree/nuget-dotnetcore

**Comment by ctaggart** [comment]
Any update on the Hub Detect 5.0.0 schedule? We really need the dotnet core support ASAP.

**Comment by utsavsanghani** [comment]
by the end of the month

**Comment by AlexRamey** [comment]
5.0.0 works as expected for this use case

**Comment by ctaggart** [comment]
We just tried out Hub Detect 5.x and the dotnet core failed on Linux with:

```
[16:15:38][Step 1/1] 2018-12-11 16:15:38 INFO  [main] --- Successfully connected to BlackDuck (version 5.0.2)!
[16:15:38][Step 1/1] 2018-12-11 16:15:38 INFO  [main] --- Configuration has finished.
[16:15:38][Step 1/1] 2018-12-11 16:15:38 INFO  [main] --- Refreshing Detect Context 2018-12-11-16-15-36-993: startup date [Tue Dec 11 16:15:38 UTC 2018]; root of context hierarchy
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Detect boot completed.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Detect will attempt to run.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Detect run begin.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Will include the docker tool.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Preparing the Docker tool.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Checking if Docker applies.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Docker was not applicable, will not actually run Docker tool.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- The properties are insufficient to run.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Docker actions finished.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Will include the detector tool.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Preparing to initialize detectors.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Building detector system.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Running detectors.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Starting search for detectors.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Searching directory: .
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- 
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ======================================================================================================
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Search results
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ======================================================================================================
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- .
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- 	APPLIES: NUGET - Solution
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ======================================================================================================
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- 
[16:15:39][Step 1/1] 2018-12-11 16:15:39 WARN  [main] --- Unable to resolve executable DOTNET
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Will use the classic inspector.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Determining the nuget inspector version.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Will attempt to resolve the classic inspector version.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Will find version from artifactory.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Found nuget inspector folder. Looking for inspector.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Searching for: IntegrationNugetInspector.exe
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Found nuget inspector: /opt/teamcity/blackduck/tools/nuget/IntegrationNugetInspector.2.5.2/tools/IntegrationNugetInspector.exe
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- 
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ======================================================================================================
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Preparation for extraction
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ======================================================================================================
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- .
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- 	 READY: NUGET - Solution
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ======================================================================================================
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- 
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Extracting 1 of 1 (0%)
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ------------------------------------------------------------------------------------------------------
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Starting extraction: NUGET - Solution
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Identifier: NUGET-0
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ------------------------------------------------------------------------------------------------------
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Running executable >/opt/teamcity/blackduck/tools/nuget/IntegrationNugetInspector.2.5.2/tools/IntegrationNugetInspector.exe --target_path=. --output_directory=/opt/teamcity/blackduck/runs/2018-12-11-16-15-36-993/extractions/NUGET-0 --ignore_failure=false --packages_repo_url=https://api.nuget.org/v3/index.json
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ------------------------------------------------------------------------------------------------------
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Finished extraction: EXCEPTION
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Code locations found: 0
[16:15:39][Step 1/1] 2018-12-11 16:15:39 ERROR [main] --- Exception:
[16:15:39][Step 1/1] 
[16:15:39][Step 1/1] com.blackducksoftware.integration.hub.detect.util.executable.ExecutableRunnerException: java.io.IOException: Cannot run program "/opt/teamcity/blackduck/tools/nuget/IntegrationNugetInspector.2.5.2/tools/IntegrationNugetInspector.exe" (in directory "."): error=13, Permission denied
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.util.executable.ExecutableRunner.runExecutable(ExecutableRunner.java:105) ~[classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.util.executable.ExecutableRunner.execute(ExecutableRunner.java:72) ~[classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.detector.nuget.inspector.ExeNugetInspector.execute(ExeNugetInspector.java:45) ~[classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.detector.nuget.NugetInspectorExtractor.extract(NugetInspectorExtractor.java:103) ~[classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.detector.nuget.NugetSolutionDetector.extract(NugetSolutionDetector.java:78) ~[classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.workflow.extraction.ExtractionManager.extract(ExtractionManager.java:89) [classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.workflow.extraction.ExtractionManager.performExtractions(ExtractionManager.java:60) [classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.workflow.detector.DetectorManager.runDetectors(DetectorManager.java:73) [classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.tool.detector.DetectorTool.performDetectors(DetectorTool.java:70) [classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.lifecycle.run.RunManager.run(RunManager.java:130) [classes!/:na]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.Application.run(Application.java:114) [classes!/:na]
[16:15:39][Step 1/1] 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:788) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
[16:15:39][Step 1/1] 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:778) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
[16:15:39][Step 1/1] 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
[16:15:39][Step 1/1] 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.Application.main(Application.java:77) [classes!/:na]
[16:15:39][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [hub-detect-5.0.0.jar:na]
[16:15:39][Step 1/1] 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [hub-detect-5.0.0.jar:na]
[16:15:39][Step 1/1] 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [hub-detect-5.0.0.jar:na]
[16:15:39][Step 1/1] 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [hub-detect-5.0.0.jar:na]
[16:15:39][Step 1/1] Caused by: java.io.IOException: Cannot run program "/opt/teamcity/blackduck/tools/nuget/IntegrationNugetInspector.2.5.2/tools/IntegrationNugetInspector.exe" (in directory "."): error=13, Permission denied
[16:15:39][Step 1/1] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	at com.blackducksoftware.integration.hub.detect.util.executable.ExecutableRunner.runExecutable(ExecutableRunner.java:83) ~[classes!/:na]
[16:15:39][Step 1/1] 	... 23 common frames omitted
[16:15:39][Step 1/1] Caused by: java.io.IOException: error=13, Permission denied
[16:15:39][Step 1/1] 	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_161]
[16:15:39][Step 1/1] 	... 24 common frames omitted
[16:15:39][Step 1/1] 
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- ------------------------------------------------------------------------------------------------------
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Finished running detectors.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Evaluating detectors for project info.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- No unique detector was found. Project info could not be found in a detector.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Finished evaluating detectors for project info.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Detector actions finished.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Completed code location tools.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Determining project info.
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Project name: fathom
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Project version: 2.2.0-build.100
[16:15:39][Step 1/1] 2018-12-11 16:15:39 INFO  [main] --- Getting or creating project.
[16:15:40][Step 1/1] 2018-12-11 16:15:40 INFO  [main] --- Completed project and version actions.
[16:15:40][Step 1/1] 2018-12-11 16:15:40 INFO  [main] --- Processing Detect Code Locations.
[16:15:40][Step 1/1] 2018-12-11 16:15:40 INFO  [main] --- Creating BDIO code locations.
```

**Comment by taikuukaits** [comment]
The new inspector requires dotnet be available: Unable to resolve executable DOTNET

This should have been better expressed, I will add additional logic to not attempt the “exe” inspector if you are on linux, which is what is happening in this log and give a better warning.

**Comment by ctaggart** [comment]
Thanks @taikuukaits, I missed that. I was looking at the stack trace. I'll get dotnet on the PATH and try again.

**Comment by taikuukaits** [comment]
This is what you will see in future versions instead:
`2018-12-11 12:13:38 INFO  [main] --- 	FAILED: NUGET - Solution - Exception occured: com.blackducksoftware.integration.hub.detect.detector.DetectorException: When not on Windows, the nuget inspector requires the dotnet executable to run.`

**Comment by Schuleboogie** [comment]
> Thanks @taikuukaits, I missed that. I was looking at the stack trace. I'll get dotnet on the PATH and try again.

Hi @ctaggart Were you able to get this working with putting dotnet on the PATH?
