### ISSUE TITLE
NugetInspectorExtractor.extract throws a NullPointerException, hub-detect ends with NoSuchElementException "error in MERGING"

### ISSUE THREAD

**Issue by ilatypov** [blackducksoftware/hub-detect#366]
## Expected behavior
* No failure in running hub-detect.
## Actual behavior
* Failure.
## Steps to Reproduce
```
08:48:53 [Open-Source Governance] 2018-12-13 08:48:53 INFO [main] --- Starting extraction: NUGET - Project
08:48:53 [Open-Source Governance] 2018-12-13 08:48:53 INFO [main] --- Identifier: NUGET-6
08:48:53 [Open-Source Governance] 2018-12-13 08:48:53 INFO [main] --- 
------------------------------------------------------------------------------------------------------
08:48:53 [Open-Source Governance] 2018-12-13 08:48:53 INFO [main] --- Running executable >C:\Program Files\dotnet\dotnet.exe C:\Users\AZXXXXXServic\blackduck\tools\nuget\BlackduckNugetInspector.0.0.6\tools\BlackduckNugetInspector.dll --target_path=.\xunit.test --output_directory=C:\Users\AZXXXXXServic\blackduck\runs\2018-12-13-13-48-45-138\extractions\NUGET-6 --ignore_failure=false --excluded_modules=Nothing_To_Exclude --packages_repo_url=https://api.nuget.org/v3/index.json --nuget_config_path=./nuget.config
08:48:53 [Open-Source Governance] 2018-12-13 08:48:53 INFO [main-Executable_Stream_Thread] --- Nuget config path did not exist.
08:48:54 [Open-Source Governance] 2018-12-13 08:48:54 INFO [main-Executable_Stream_Thread] --- Succesfully added dependency info resource: https://api.nuget.org/v3/index.json
08:48:54 [Open-Source Governance] 2018-12-13 08:48:54 INFO [main] --- Executable finished: 0
08:48:54 [Open-Source Governance] 2018-12-13 08:48:54 INFO [main] --- ------------------------------------------------------------------------------------------------------
08:48:54 [Open-Source Governance] 2018-12-13 08:48:54 INFO [main] --- Finished extraction: EXCEPTION
08:48:54 [Open-Source Governance] 2018-12-13 08:48:54 INFO [main] --- Code locations found: 0
08:48:54 [Open-Source Governance] 2018-12-13 08:48:54 ERROR [main] --- Exception:
08:48:54 [Open-Source Governance]
08:48:54 [Open-Source Governance] java.lang.NullPointerException: null
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.detector.nuget.NugetInspectorExtractor.extract(NugetInspectorExtractor.java:112) ~[classes!/:na]
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.detector.nuget.NugetProjectDetector.extract(NugetProjectDetector.java:123) ~[classes!/:na]
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.workflow.extraction.ExtractionManager.extract(ExtractionManager.java:89) [classes!/:na]
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.workflow.extraction.ExtractionManager.performExtractions(ExtractionManager.java:60) [classes!/:na]
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.workflow.detector.DetectorManager.runDetectors(DetectorManager.java:73) [classes!/:na]
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.tool.detector.DetectorTool.performDetectors(DetectorTool.java:70) [classes!/:na]
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.lifecycle.run.RunManager.run(RunManager.java:130) [classes!/:na]
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.Application.run(Application.java:114) [classes!/:na]
08:48:54 [Open-Source Governance] at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:788) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
08:48:54 [Open-Source Governance] at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:778) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
08:48:54 [Open-Source Governance] at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
08:48:54 [Open-Source Governance] at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137) [spring-boot-2.0.3.RELEASE.jar!/:2.0.3.RELEASE]
08:48:54 [Open-Source Governance] at com.blackducksoftware.integration.hub.detect.Application.main(Application.java:77) [classes!/:na]
08:48:54 [Open-Source Governance] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
08:48:54 [Open-Source Governance] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
08:48:54 [Open-Source Governance] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
08:48:54 [Open-Source Governance] at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
08:48:54 [Open-Source Governance] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [hub-detect-5.0.1.jar:na]
08:48:54 [Open-Source Governance] at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [hub-detect-5.0.1.jar:na]
08:48:54 [Open-Source Governance] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [hub-detect-5.0.1.jar:na]
08:48:54 [Open-Source Governance] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [hub-detect-5.0.1.jar:na]

...


08:49:04 [Open-Source Governance] 2018-12-13 08:49:03 INFO [main] --- Waiting for the BOM to be updated
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 ERROR [main] --- Detect run failed.
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 ERROR [main] --- There was a problem: There was a problem in the Hub processing the scan(s). Error Status : ERROR, Error in MERGING, java.util.NoSuchElementException [b81242c2-8bdc-474c-a3c2-2006ec361b26]
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Detect will attempt to shutdown.
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Detect shutdown begin.
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Detect will cleanup.
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Detect shutdown completed.
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- All detect actions completed.
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] ---
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- ======================================================================================================
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Detector Issue Summary
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- ======================================================================================================
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- .\ACS.console
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Exception: NUGET - Project
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- java.lang.NullPointerException
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- .\ACS.service
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Exception: NUGET - Project
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- java.lang.NullPointerException
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- .\IC.api
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Exception: NUGET - Project
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- java.lang.NullPointerException
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- .\IC.console
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Exception: NUGET - Project
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- java.lang.NullPointerException
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- .\IC.service
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Exception: NUGET - Project
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- java.lang.NullPointerException
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- .\xunit.test
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Exception: NUGET - Project
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- java.lang.NullPointerException
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- ======================================================================================================
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] ---
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] ---
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] ---
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- ======== Detect Results ========
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- NUGET: FAILURE
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Overall Status: FAILURE_DETECTOR
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- ================================
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] ---
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 INFO [main] --- Detect duration: 00h 00m 19s 108ms
08:49:04 [Open-Source Governance] 2018-12-13 08:49:04 ERROR [main] --- Exiting with code 5 - FAILURE_DETECTOR
```
## Versions
* HubDetect 5.0.1
* DotNet Core
* BlackduckNugetInspector 0.0.6
* Windows 2012

**Comment by taikuukaits** [comment]
Do you have a full log?

**Comment by akamen** [comment]
No response from @ilatypov

**Comment by ilatypov** [comment]
Absence of the full log does not resolve the issue.  Please have a good faith in your customer.
